### PR TITLE
operationRef matching referenced OpenAPI description

### PR DESCRIPTION
**Pull request by ralfhandl**
And the subsequent `parameters` block

### CODE REVIEW

**Comment by gcatanese** [comment]
According to OpenAPI Workflow spec [v1.0.0](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md#fixed-fields-4) `"The operation being referenced MUST be described within one of the source descriptions."`.

If I understand correctly this means the `operationRef`  should refer to `./pet-coupons.openapi.yaml` that is mentioned in `sourceDescriptions`

**Comment by ralfhandl** [comment]
> If I understand correctly this means the `operationRef` should refer to `./pet-coupons.openapi.yaml` that is mentioned in `sourceDescriptions`

Good point, so not only the fragment part of the example operationRef needs repair, the path part also has room for improvement 😄

**Comment by ralfhandl** [comment]
@frankkilcommins Please review

**Review by frankkilcommins — APPROVED** [review]
LGTM. Thanks for these fixes @ralfhandl and yes as @gcatanese the operations being referenced should be located within a `sourceDescription`

**Pull request merged**
